// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALkexuoehLaVrPZDK6dgYydi-7LugeiSg',
    appId: '1:684928042172:web:0ea5c81928df3abc63fcb9',
    messagingSenderId: '684928042172',
    projectId: 'restaurant-booking-929fd',
    authDomain: 'restaurant-booking-929fd.firebaseapp.com',
    storageBucket: 'restaurant-booking-929fd.firebasestorage.app',
    measurementId: 'G-NHSYEVEH4W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgFKqwtYGPW8RyDdzA507Ng_sWNDOiHEM',
    appId: '1:684928042172:android:4d9ae252d568d6da63fcb9',
    messagingSenderId: '684928042172',
    projectId: 'restaurant-booking-929fd',
    storageBucket: 'restaurant-booking-929fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtqPr9wFe-8Pe1wB7fmHdm9Uw1yh4cIws',
    appId: '1:684928042172:ios:b3d9ad1da52f686563fcb9',
    messagingSenderId: '684928042172',
    projectId: 'restaurant-booking-929fd',
    storageBucket: 'restaurant-booking-929fd.firebasestorage.app',
    iosBundleId: 'com.example.restaurantBookingSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtqPr9wFe-8Pe1wB7fmHdm9Uw1yh4cIws',
    appId: '1:684928042172:ios:b3d9ad1da52f686563fcb9',
    messagingSenderId: '684928042172',
    projectId: 'restaurant-booking-929fd',
    storageBucket: 'restaurant-booking-929fd.firebasestorage.app',
    iosBundleId: 'com.example.restaurantBookingSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALkexuoehLaVrPZDK6dgYydi-7LugeiSg',
    appId: '1:684928042172:web:b2ccd415b53af5b763fcb9',
    messagingSenderId: '684928042172',
    projectId: 'restaurant-booking-929fd',
    authDomain: 'restaurant-booking-929fd.firebaseapp.com',
    storageBucket: 'restaurant-booking-929fd.firebasestorage.app',
    measurementId: 'G-QZQ3CBMHFH',
  );
}
